apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: busybox 
    command: ["/bin/sh", "-c", "env" ]
    env:
    - name: MYSQL_ADMIN_USERNAME 
      valueFrom:
        secretKeyRef:
          name: mysql-login-credentials
          key: username 
    - name: MYSQL_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-login-credentials
          key: password 
  restartPolicy: Never



